### ISSUE TITLE
work on the database

### ISSUE THREAD

**Issue by ciarrastevenett** [ciarrastevenett/Scrapbooker-2020#7]
get a database useable to for our product

**Comment by za01br** [comment]
- [x] Create main database

- [x] Create tables: Images, Albums, and Tags (3)

- [x] Save every new image from scan/drag-n-drop into new row in Images tables

- [x] Browse Page: query the database to show all images in Images table

- [ ] Detail page: Query the database with the filname comming from the click on Browse image
