### ISSUE TITLE
finishing browse page

### ISSUE THREAD

**Issue by ciarrastevenett** [ciarrastevenett/Scrapbooker-2020#8]
- [x] Transform each thumbnail in a link that redirects to the Detail Page

- [x] Make sure pictures are side by side

- [x] Make sure the pictures are pulling directly from Database

**Comment by za01br** [comment]
@ciarrastevenett  I think this not finished yet.
Per the issue description:
"**Transform each thumbnail in a link that redirects to the Detail Page**
Make sure pictures are side by side"
